name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appdirs
  - asn1crypto
  - attrs
  - backcall
  - blas
  - bleach
  - bokeh
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - clangdev
  - click
  - cloudpickle
  - constantly
  - cryptography
  - cryptography-vectors
  - cycler
  - cytoolz
  - dask
  - dask-core
  - dbus
  - decorator
  - defusedxml
  - distributed
  - entrypoints
  - expat
  - ffmpeg
  - fontconfig
  - freetype
  - gettext
  - giflib
  - glib
  - gmp
  - gnutls
  - graphite2
  - harfbuzz
  - hdf5
  - heapdict
  - html5lib
  - icu
  - idna
  - imageio
  - incremental
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jasper
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - lame
  - libblas
  - libcblas
  - libedit
  - libffi
  - libiconv
  - liblapack
  - liblapacke
  - libopenblas
  - libopus
  - libpng
  - libsodium
  - libtiff
  - libvpx
  - libwebp
  - libxml2
  - llvm-meta
  - llvmdev
  - locket
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl_fft
  - mkl_random
  - msgpack-python
  - nbconvert
  - nbformat
  - ncurses
  - nettle
  - networkx
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openblas
  - opencv=4.0.1
  - openh264
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - partd
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - prometheus_client
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pyasn1
  - pycosat
  - pycparser
  - pygments
  - pyhamcrest
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - regex
  - requests
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy
  - send2trash
  - service_identity
  - setuptools
  - simplegeneric
  - sip
  - six
  - sortedcontainers
  - sqlite
  - tblib
  - terminado
  - testpath
  - tk
  - toolz
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - x264
  - xz
  - yaml
  - zeromq
  - zict
  - zlib
  - zope.interface
  - zstd
  - lz4-c
