name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=2.1.4
  - bokeh=1.0.4
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - cairo=1.14.12
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - clangdev=6.0.1
  - click=6.7
  - cloudpickle=0.5.3
  - conda=4.6.8
  - conda-env=2.6.0
  - constantly=15.1.0
  - cryptography=2.6.1
  - cryptography-vectors=2.6.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=0.18.2
  - dask-core=0.18.2
  - dbus=1.13.0
  - decorator=4.3.0
  - distributed=1.26.0
  - entrypoints=0.3
  - expat=2.2.5
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.55.0
  - graphite2=1.3.13
  - harfbuzz=1.9.0
  - hdf5=1.10.2
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.3.0
  - incremental=17.5.0
  - intel-openmp=2018.0.3
  - ipykernel=4.8.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.0
  - jasper=2.0.14
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.2.20
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.35
  - libsodium=1.0.16
  - libtiff=4.0.9
  - libvpx=1.7.0
  - libxml2=2.9.8
  - llvm-meta=6.0.1
  - llvmdev=6.0.1
  - locket=0.2.0
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.11
  - mkl_random=1.0.2
  - msgpack-python=0.6.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.1
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.45.1
  - openblas=0.3.5
  - opencv=3.4.2
  - openssl=1.1.1
  - packaging=17.1
  - pandas=0.24.2
  - pandoc=2.2.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - partd=0.3.8
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - pixman=0.34.0
  - psutil=5.6.1
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pyasn1=0.4.4
  - pycosat=0.6.3
  - pycparser=2.18
  - pygments=2.2.0
  - pyhamcrest=1.9.0
  - pyopenssl=19.0.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - python=3.7.3
  - python-dateutil=2.7.3
  - python.app=1.2
  - pytz=2018.5
  - pywavelets=1.0.2
  - pyyaml=5.1
  - pyzmq=18.0.1
  - qt=5.6.2
  - qtconsole=4.4.0
  - readline=7.0
  - regex=2019.03.12
  - requests=2.21.0
  - ruamel_yaml=0.15.71
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.8.0
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.12.0
  - sortedcontainers=2.0.4
  - sqlite=3.26.0
  - tblib=1.3.2
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.2
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - zope.interface=4.6.0
